### ISSUE TITLE
Runtime error line 82

### ISSUE THREAD

**Issue by jordanblakey** [stmorgan/pythonNNexample#2]
This line produces a syntax error on my machine: 

```82 |  print "Error: " + str(np.mean(np.abs(l2_error)))```

**Comment by robertlugg** [comment]
My guess is that you are using python 3.x.  From python 2 to python 3, they changed print.  print was a command and now its a function.  put everything is parens:
 print ("Error: " + str(np.mean(np.abs(l2_error))))

It would be possible for the author to make the code work for both versions of python but of course that would add to the complexity.  Oh, and be sure to change the other print lines too :)

**Comment by stmorgan** [comment]
robertlugg: Yes, you are correct. The print statement needs to be converted to Python 3 form.

**Comment by stmorgan** [comment]
I've modified the 'print' and 'xrange' (changed to 'range') statements so that the program runs on both Python2 and Python3. Note that if you are running the code outside of a Jupyter notebook, you will get an error the the final Jupyter command that embeds Siraj's YouTube video. You can safely delete this line.
